### ISSUE TITLE
groups.js is JavaScript, not JSON

### ISSUE THREAD

**Issue by ajorg** [zarya/BrandMeister-Dashboard#14]
I'd like to consume groups.js in a script, but my json parser won't parse it because it has `var groups =` at the top and a `;` at the bottom. I wonder if you would consider using JSON format for this and other static data files so that they can be consumed by other applications.

**Comment by zarya** [comment]
Yes it could be json i could rewrite some of the internals of the dashboard to make the source file json

I will put it on the list of things to do.

**Comment by candrist** [comment]
I wrote the following python script. I load all the talkgroups, repeaters and users into a mysql server every 2 days.

Here is the talkgroups portion of the script.

```
TALKGROUPS_URL = "https://brandmeister.network/dist/js/bm/groups.js"
talkgroupsString = unicode(urllib.urlopen(TALKGROUPS_URL).read(), "ISO-8859-1")
talkgroupsString = talkgroupsString.replace('var groups =', '')
talkgroupsString = talkgroupsString.replace(';', '')
talkgroupsDictionary = eval(talkgroupsString)
talkgroups = collections.OrderedDict(sorted(talkgroupsDictionary.items()))

dbdeletet = "DELETE FROM talkgroups"
db.execute(dbdeletet)
for keys,values in talkgroups.items():
    dbinsertt = "INSERT INTO talkgroups (talkgroupid, talkgroupdesc) VALUES ('{}', '{}')".format(keys, values)
    db.execute(dbinsertt)
```

Hope that helps.

**Comment by zarya** [comment]
the encoding is UTF-8 not ISO-8859-1 ;)

and here is a link for getting the file in json format https://brandmeister.network/interfaces/groups.php
